version: '3.3'

services:
  influxdb:
    image: influxdb:2.7
    container_name: flashes-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=flashes
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}

  mongodb:
    image: mongo:latest
    container_name: flashes-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_PATH=/data/db
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  grafana:
    image: grafana/grafana:latest
    container_name: flashes-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana

  backend:
    build: ./backend
    container_name: flashes-backend
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - mongodb
    volumes:
      - ./backend:/app
